@forward-modifiers Shift Control Alt
@allow-unmapped-commands
@enforce-lowercase-commands

# Aliases to make rules easier to read
whichkey = Virtual1
windows = Virtual2

# Mappings
CapsLock >> whichkey ^ !whichkey
(Meta){W} >> windows ^ !windows

# Macros
type   = $(keymapperctl --type "$0")
niri = $(niri msg action "$0") ^
dms = $(dms ipc call $0) ^
trigger  = ? "$0" >> repeat[Backspace, sub[length["$0"], 1]] $1
complete = ? "$0" Tab >> $1
format_date = $(date +"$0")

# Replacements

## Data and time
trigger[":time", type[format_date["%H:%M:%S"]]]
trigger[":date", type[format_date["%Y-%m-%d"]]]
trigger[":dt",   type[format_date["%Y-%m-%d %H:%M:%S"]]]
trigger[":ts",   type[format_date["%s"]]]

## Auth
trigger[":email",    type["darkliquid@darkliquid.co.uk"]]
trigger[":genpass",  type[$(rbw gen 16 --nonconfusables)]]
trigger[":genwords", type[$(rbw gen 8 --diceware)]]
trigger[":genhex",   type[$(openssl rand -hex 16)]]

## Emoji
trigger[":flip",   type["(╯'□')╯︵ ┻━┻"]]
trigger[":unflip", type["┬─┬ ノ( ゜-゜ノ)"]]
trigger[":shrug",  type["¯\\_(ツ)_/¯"]]
trigger[":lenny",  type["( ͡° ͜ʖ ͡°)"]]

## Misc
trigger[":ip",   type[$(dig @resolver1.opendns.com ANY myip.opendns.com +short)]]
trigger[":uuid", type[$(uuidgen)]]

# Commands

## Whichkeys
whichkey >> $(wk --key-chords ~/.config/whichkeys.wks)
!whichkey >> Escape

## Windowing
windows{ArrowUp} >> niri["focus-window-up-or-bottom"]
windows{ArrowDown} >> niri["focus-window-down-or-top"]
windows{ArrowLeft} >> niri["focus-column-left-or-last"]
windows{ArrowRight} >> niri["focus-column-right-or-first"]
windows{F} >> niri["maximize-column"]
windows{O} >> niri["toggle-overview"]
windows{R} >> niri["switch-preset-column-width"]
windows{Q} >> niri["close-window"]

## Misc
(Meta){Space} >> dms["launcher toggle"]
(Meta){A} >> dms["plugins toggle aiAssistant"]
(Meta){Slash} >> $(wat)