[settings]
npm.package_manager = "bun"

[tools]
age = "latest"
"aqua:dalance/procs" = "latest"
"aqua:dolthub/dolt" = "latest"
"aqua:steveyegge/beads" = "latest"
ast-grep = "latest"
bat = "latest"
bun = "latest"
claude = "latest"
colima = "latest"
crush = "latest"
delta = "latest"
docker-cli = "latest"
eza = "latest"
fx = "latest"
fzf = "latest"
gemini = "latest"
gh = "latest"
github-cli = "latest"
"github:CtrlSpice/otel-desktop-viewer" = "latest"
"github:JanDeDobbeleer/aliae" = "latest"
"github:Rodrigodd/strace-tui" = "latest"
"github:gromgit/pup" = "latest"
"github:pol-rivero/doot" = "latest"
"github:pol-rivero/pkgstate" = "latest"
"github:pomdtr/sunbeam" = "latest"
"github:ymtdzzz/otel-tui" = "latest"
go = "latest"
golangci-lint = "latest"
goreleaser = "latest"
gum = "latest"
hexyl = "latest"
imagemagick = "latest"
jc = "latest"
jq = "latest"
lazygit = "latest"
lima = "latest"
neovim = "nightly"
node = "latest"
npm = "latest"
"npm:@continuedev/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:beads-ui" = "latest"
ollama = "latest"
"pipx:beads-mcp" = "latest"
prettier = "latest"
ripgrep = "latest"
rust = "latest"
rust-analyzer = "latest"
starship = "latest"
task = "latest"
usage = "latest"
uv = "latest"
xh = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"

[tasks.system-update]
hide = true
description = "Run various updates"
run = [
    'doot pull',
    'cachy-update',
    'mise self-update',
    'mise upgrade --bump',
    'code --update-extensions',
    'nvim --headless "+Lazy! sync" +qa'
]
